"""
Get Supabase Connection String from Dashboard
This script helps you find the correct database connection string
"""
import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv('SUPABASE_URL')
PROJECT_REF = SUPABASE_URL.split('//')[1].split('.')[0] if SUPABASE_URL else None

print("=" * 70)
print("SUPABASE DATABASE CONNECTION STRING GUIDE")
print("=" * 70)
print()
print(f"Your Supabase Project Reference: {PROJECT_REF}")
print(f"Your Supabase URL: {SUPABASE_URL}")
print()
print("To get the correct database connection string:")
print()
print("1. Go to: https://supabase.com/dashboard/project/" + PROJECT_REF)
print("2. Click 'Settings' (gear icon) → 'Database'")
print("3. Scroll down to 'Connection string' section")
print("4. You'll see multiple connection options:")
print()
print("   Option A: Session Pooler (Recommended)")
print("   -----------------------------------------")
print("   • Port: 5432")
print("   • Best for: Web applications, long-running connections")
print("   • Connection string format:")
print("     postgresql://postgres.[PROJECT-REF]:[PASSWORD]@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres")
print()
print("   Option B: Transaction Pooler")
print("   -----------------------------")
print("   • Port: 6543")
print("   • Best for: Serverless functions, short connections")
print("   • Connection string format:")
print("     postgresql://postgres.[PROJECT-REF]:[PASSWORD]@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres")
print()
print("   Option C: Direct Connection")
print("   ----------------------------")
print("   • Port: 5432")
print("   • Requires IPv6")
print("   • May not work from all networks")
print()
print("5. Copy the connection string (choose Session Pooler)")
print("6. Replace [YOUR-PASSWORD] with: Kidscommerce@1234")
print("7. For Python/SQLAlchemy, change 'postgresql://' to 'postgresql+psycopg2://'")
print("8. URL-encode the password: Kidscommerce@1234 → Kidscommerce%401234")
print()
print("Expected format for your .env file:")
print("-" * 70)
print(f'SUPABASE_DB_URL="postgresql+psycopg2://postgres.{PROJECT_REF}:Kidscommerce%401234@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"')
print("-" * 70)
print()
print("After updating .env, restart your Flask server.")
print()
print("=" * 70)
