"""
Unit tests for RollbackService
Tests disaster recovery functionality for unified chat migration
"""

import os
import pytest
import tempfile
from unittest.mock import Mock, patch, MagicMock
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, Session
from migration_service import RollbackService
from typing import Dict, List


class TestRollbackService:
    """Test suite for RollbackService"""
    
    @pytest.fixture
    def mock_db_session(self):
        """Create a mock database session"""
        session = Mock(spec=Session)
        session.execute = Mock()
        session.commit = Mock()
        session.rollback = Mock()
        return session
    
    @pytest.fixture
    def temp_backup_files(self):
        """Create temporary backup files for testing"""
        # Create temporary directory
        temp_dir = tempfile.mkdtemp()
        
        # Create backup files with sample SQL (matching actual backup format)
        store_backup_path = os.path.join(temp_dir, 'store_chat_backup.sql')
        rider_backup_path = os.path.join(temp_dir, 'rider_chat_backup.sql')
        
        store_backup_sql = """-- Backup of store_chat_message
-- Created: 20240115_143022
-- Records: 1
-- Generated by MigrationService

-- Table: store_chat_message
-- Columns: id, buyer_id, seller_id, sender_role, message, product_id, is_read, created_at

INSERT INTO store_chat_message (id, buyer_id, seller_id, sender_role, message, product_id, is_read, created_at) VALUES (1, 1, 2, 'buyer', 'Test message', 100, FALSE, '2024-01-15T14:30:22');
"""
        
        rider_backup_sql = """-- Backup of rider_chat_message
-- Created: 20240115_143022
-- Records: 1
-- Generated by MigrationService

-- Table: rider_chat_message
-- Columns: id, buyer_id, rider_id, sender_role, message, order_id, is_read, created_at

INSERT INTO rider_chat_message (id, buyer_id, rider_id, sender_role, message, order_id, is_read, created_at) VALUES (1, 1, 3, 'buyer', 'Test delivery message', 200, FALSE, '2024-01-15T14:30:22');
"""
        
        with open(store_backup_path, 'w') as f:
            f.write(store_backup_sql)
        
        with open(rider_backup_path, 'w') as f:
            f.write(rider_backup_sql)
        
        backup_paths = {
            'store_chat_backup': store_backup_path,
            'rider_chat_backup': rider_backup_path
        }
        
        yield backup_paths
        
        # Cleanup
        os.remove(store_backup_path)
        os.remove(rider_backup_path)
        os.rmdir(temp_dir)
    
    def test_init(self, mock_db_session, temp_backup_files):
        """Test RollbackService initialization"""
        service = RollbackService(mock_db_session, temp_backup_files)
        
        assert service.db == mock_db_session
        assert service.backup_paths == temp_backup_files
    
    def test_clear_unified_table_success(self, mock_db_session):
        """Test successful clearing of ChatMessage table"""
        # Mock count queries
        mock_result_before = Mock()
        mock_result_before.scalar.return_value = 100
        
        mock_result_after = Mock()
        mock_result_after.scalar.return_value = 0
        
        mock_db_session.execute.side_effect = [
            mock_result_before,  # Count before
            None,                # TRUNCATE
            mock_result_after    # Count after
        ]
        
        backup_paths = {'store_chat': '/fake/path1', 'rider_chat': '/fake/path2'}
        service = RollbackService(mock_db_session, backup_paths)
        
        result = service.clear_unified_table()
        
        assert result is True
        assert mock_db_session.commit.called
        
        # Verify execute was called (for TRUNCATE)
        assert mock_db_session.execute.call_count >= 2
    
    def test_clear_unified_table_failure(self, mock_db_session):
        """Test failure when clearing ChatMessage table"""
        # Mock exception during truncate
        mock_db_session.execute.side_effect = Exception("Database error")
        
        backup_paths = {'store_chat': '/fake/path1', 'rider_chat': '/fake/path2'}
        service = RollbackService(mock_db_session, backup_paths)
        
        result = service.clear_unified_table()
        
        assert result is False
        assert mock_db_session.rollback.called
    
    def test_restore_legacy_tables_missing_backup(self, mock_db_session):
        """Test restore handles missing backup files gracefully"""
        backup_paths = {
            'store_chat_backup': '/nonexistent/path1.sql',
            'rider_chat_backup': '/nonexistent/path2.sql'
        }
        service = RollbackService(mock_db_session, backup_paths)
        
        result = service.restore_legacy_tables()
        
        # Should fail because files don't exist
        assert result is False
    
    def test_restore_legacy_tables_empty_backup(self, mock_db_session):
        """Test restore handles empty backup files"""
        # Create empty backup files
        temp_dir = tempfile.mkdtemp()
        empty_backup = os.path.join(temp_dir, 'empty_backup.sql')
        
        with open(empty_backup, 'w') as f:
            f.write('')
        
        backup_paths = {'store_chat_backup': empty_backup}
        service = RollbackService(mock_db_session, backup_paths)
        
        # Mock the database operations
        mock_db_session.execute.return_value = None
        
        result = service.restore_legacy_tables()
        
        # Should succeed but restore 0 records
        assert result is True
        
        # Cleanup
        os.remove(empty_backup)
        os.rmdir(temp_dir)
    
    def test_restore_legacy_tables_success(self, mock_db_session, temp_backup_files):
        """Test successful restoration of legacy tables"""
        # Mock successful execution
        mock_result = Mock()
        mock_result.scalar.return_value = 1  # 1 record restored
        
        mock_db_session.execute.return_value = mock_result
        
        service = RollbackService(mock_db_session, temp_backup_files)
        
        result = service.restore_legacy_tables()
        
        assert result is True
        assert mock_db_session.commit.called
        
        # Verify execute was called multiple times (TRUNCATE + INSERTs)
        assert mock_db_session.execute.call_count >= 4
    
    def test_execute_rollback_success(self, mock_db_session, temp_backup_files):
        """Test successful complete rollback workflow"""
        # Mock successful operations
        mock_result_count = Mock()
        mock_result_count.scalar.return_value = 0
        
        mock_db_session.execute.return_value = mock_result_count
        
        service = RollbackService(mock_db_session, temp_backup_files)
        
        result = service.execute_rollback("Test rollback reason")
        
        assert isinstance(result, dict)
        assert result['success'] is True
        assert result['reason'] == "Test rollback reason"
        assert result['restored_legacy'] is True
        assert result['cleared_unified'] is True
        assert len(result['logs']) > 0
        assert result['timestamp'] is not None
    
    def test_execute_rollback_partial_failure(self, mock_db_session):
        """Test rollback with partial failure"""
        # Mock failure in clearing unified table
        mock_db_session.execute.side_effect = Exception("Database error")
        
        backup_paths = {
            'store_chat': '/nonexistent/path1.sql',
            'rider_chat': '/nonexistent/path2.sql'
        }
        service = RollbackService(mock_db_session, backup_paths)
        
        result = service.execute_rollback("Test failure scenario")
        
        assert isinstance(result, dict)
        assert result['success'] is False
        assert result['reason'] == "Test failure scenario"
        assert len(result['logs']) > 0
    
    def test_execute_rollback_logs_operations(self, mock_db_session, temp_backup_files, caplog):
        """Test that rollback logs all operations"""
        import logging
        caplog.set_level(logging.INFO)
        
        # Mock successful operations
        mock_result = Mock()
        mock_result.scalar.return_value = 0
        mock_db_session.execute.return_value = mock_result
        
        service = RollbackService(mock_db_session, temp_backup_files)
        
        result = service.execute_rollback("Test logging")
        
        # Verify logging occurred (check for actual log message)
        assert "INITIATING ROLLBACK PROCEDURE" in caplog.text
        assert "Test logging" in caplog.text
        assert "Clearing unified ChatMessage table" in caplog.text
        assert "Restoring legacy tables" in caplog.text
    
    def test_restore_table_handles_multiple_statements(self, mock_db_session, temp_backup_files):
        """Test restoration handles multiple SQL statements correctly"""
        # Mock successful execution
        mock_result = Mock()
        mock_result.scalar.return_value = 1
        mock_db_session.execute.return_value = mock_result
        
        service = RollbackService(mock_db_session, temp_backup_files)
        
        # Test the public method instead of private method
        result = service.restore_legacy_tables()
        
        assert result is True
        
        # Verify multiple execute calls (TRUNCATE + INSERTs for both tables)
        assert mock_db_session.execute.call_count >= 4


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
